# ===============================
# Database connection
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345678


# ===============================
# Access token & Refresh token
# ===============================
ACCESS_TOKEN_SECRET_KEY=vS6v8m9X6pWp4z9B2nL5vT8xK3mQ7rJ1aU9zY4wX2eI=
ACCESS_TOKEN_EXPIRATION_Time=100000

REFRESH_TOKEN_SECRET_KEY=aS6v8m9X6pWp4z9B2nL5vT8xK3nU7rJ1aU9zY4wX2eIy
REFRESH_TOKEN_EXPIATION_TIME=3600000